# Generated by Django 4.2.7 on 2023-11-11 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Logo')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Company Name')),
                ('cin', models.CharField(max_length=21, null=True, verbose_name='Company Identification Number')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('classification', models.CharField(choices=[('Micro', 'Micro'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=100, null=True, verbose_name='Classification')),
                ('industry', models.CharField(max_length=100, null=True, verbose_name='Industry Type')),
                ('revenue', models.FloatField(verbose_name='Revenue per Annum')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Company Name')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Address')),
                ('type', models.CharField(choices=[('Inflow', 'Inflow'), ('Outflow', 'Outflow')], max_length=100, null=True, verbose_name='Type')),
                ('value', models.FloatField(verbose_name='Expected Value')),
                ('unit', models.CharField(choices=[('Ton', 'Ton'), ('Kg', 'Kg'), ('Lt', 'Lt')], max_length=100, null=True, verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_accepted', models.DateTimeField(verbose_name='Date Accepted')),
                ('target', models.FloatField(verbose_name='Target Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('Ton', 'Ton'), ('Kg', 'Kg'), ('Lt', 'Lt')], max_length=100, null=True, verbose_name='Unit')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Acknowledged', 'Acknowledged'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], max_length=100, null=True, verbose_name='Status')),
                ('buyer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to='app.company')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('seller', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.FloatField(verbose_name='Paid Amount')),
                ('unpaid', models.FloatField(verbose_name='Unpaid Amount')),
                ('total', models.FloatField(verbose_name='Total Amount')),
                ('commission', models.FloatField(verbose_name='Commission')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('Ton', 'Ton'), ('Kg', 'Kg'), ('Lt', 'Lt')], max_length=100, null=True, verbose_name='Unit')),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=100, null=True, verbose_name='Status')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('quotation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Inflow', 'Inflow'), ('Outflow', 'Outflow')], max_length=100, null=True, verbose_name='Type')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('required', models.IntegerField(null=True, verbose_name='Required Quantity')),
                ('unit', models.CharField(choices=[('Ton', 'Ton'), ('Kg', 'Kg'), ('Lt', 'Lt')], max_length=100, null=True, verbose_name='Unit')),
                ('value', models.FloatField(null=True, verbose_name='Value')),
                ('last_updated', models.DateTimeField(null=True, verbose_name='Date Last Updated')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('transactions', models.ManyToManyField(blank=True, to='app.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAddress', models.CharField(max_length=500, null=True, verbose_name='From Address')),
                ('toAddress', models.CharField(max_length=500, null=True, verbose_name='To Address')),
                ('orderDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Order Date')),
                ('shipDate', models.DateTimeField(null=True, verbose_name='Shipped Date')),
                ('estimatedDate', models.DateTimeField(null=True, verbose_name='Estimated Delivery Date')),
                ('deliveryDate', models.DateTimeField(null=True, verbose_name='Delivery Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('Ton', 'Ton'), ('Kg', 'Kg'), ('Lt', 'Lt')], max_length=100, null=True, verbose_name='Unit')),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=100, null=True, verbose_name='Status')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='inflow',
            field=models.ManyToManyField(blank=True, related_name='Inflow_Products', to='app.product'),
        ),
        migrations.AddField(
            model_name='company',
            name='outflow',
            field=models.ManyToManyField(blank=True, related_name='Outflow_Products', to='app.product'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
